### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by EvgeniyaL** [SoftUni-Java-Fundamentals-Project/Java-Fundametals-Project#2]
We need to add javadoc to all methods and export the in a documentation file.

**Comment by EvgeniyaL** [comment]
Only Field.java needs to be documented.

**Comment by baxlash** [comment]
I added documentation for the field class.
There are 2 method I could not describ what they are exactly doing.

**Comment by EvgeniyaL** [comment]
Okay I will see them :)
